export const cards = [
  {
    id: 1,
    title: "Magnus Carlsen",
    subtitle: "World Champion",
    description: "ნორვეგიელი შახმატის გენიოსი. 5-ჯერ მსოფლიო ჩემპიონი და ყველა დროის უმაღლესი რეიტინგის მოთამაშე.",
    rating: 2830,
    country: "🇳🇴 ნორვეგია",
    category: "Grandmaster",
    image: "https://images.chesscomfiles.com/uploads/v1/master_player/3b0ddf4e-bd82-11e8-9421-af517c2ebfed.f2dc9e34.250x250o.5ede81456fe8@2x.png",
    color: "#1a1a2e",
    accent: "#e94560",
  },
  {
    id: 2,
    title: "Fabiano Caruana",
    subtitle: "Super Grandmaster",
    description: "ამერიკელი გრანდ-მაესტრო, 2018 წლის მსოფლიო ჩემპიონატის ფინალისტი. კლასიკურ პარტიებში უძლეველი.",
    rating: 2805,
    country: "🇺🇸 ამერიკა",
    category: "Grandmaster",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9xcG5h-O6C4fDde6ZxpsqlWeHwCg5IyS2RC1qW8_jgZNQn2Ou8z0t0BdkThxpjFsfJGPHXcw8Z0kRtQtJMr6IRvpPiMx4P4chupdGZz_f&s=10",
    color: "#16213e",
    accent: "#0f3460",
  },
  {
    id: 3,
    title: "Hikaru Nakamura",
    subtitle: "Rapid & Blitz King",
    description: "ამერიკელი სენსაცია, რომელიც ბლიც შახმატში ყველაზე ძლიერია. Twitch-ის სტრიმინგის მეფე.",
    rating: 2794,
    country: "🇺🇸 ამერიკა",
    category: "Grandmaster",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Nakamura_Hikaru_%2829290269410%29_%28cropped%29_%28cropped%29.jpg",
    color: "#1b1b2f",
    accent: "#e84545",
  },
  {
    id: 4,
    title: "Ding Liren",
    subtitle: "მსოფლიო ჩემპიონი 2023",
    description: "ჩინელი გრანდ-მაესტრო და 2023 წლის მსოფლიო ჩემპიონი. სტრატეგიული სიღრმე და ფსიქოლოგიური სიმყარე.",
    rating: 2762,
    country: "🇨🇳 ჩინეთი",
    category: "Grandmaster",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/DingLiren24a.jpg/960px-DingLiren24a.jpg",
    color: "#150e1f",
    accent: "#f5a623",
  },
  {
    id: 5,
    title: "Garry Kasparov",
    subtitle: "ლეგენდა",
    description: "ყველა დროის უდიდესი შახმატელი. 1985-2000 წლებში მსოფლიო ჩემპიონი, გამოიგონა 'კასპაროვის სტილი'.",
    rating: 2851,
    country: "🇦🇿 აზერბაიჯანი",
    category: "Legend",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Garri_Kasparow_%2818776605665%29_%28cropped%29_2.jpg",
    color: "#0d0d0d",
    accent: "#c0392b",
  },
  {
    id: 6,
    title: "Judit Polgár",
    subtitle: "ქალი-გრანდ-მაესტრო",
    description: "ისტორიის ყველაზე ძლიერი ქალი შახმატელი. გაანადგურა კასპაროვი, ანანდი და ყველა ლეგენდა.",
    rating: 2735,
    country: "🇭🇺 უნგრეთი",
    category: "Legend",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Judit_Polg%C3%A1r_2013.jpg/500px-Judit_Polg%C3%A1r_2013.jpg",
    color: "#1a0a2e",
    accent: "#9b59b6",
  },
];
 